//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int Horizontal = 0;
    public const int Vertical = 1;
    public const int RotateLeft = 2;
    public const int RotateRight = 3;
    public const int Boost = 4;
}
